version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: Tienda
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: BDTienda
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - "3309:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - db_network

networks:
  db_network:
    driver: bridge